version: '3.1'

services:
    backend:
        build: ./docker/php/
        ports:
            - "80:80"
        volumes:
            - ./src/backend/:/var/www/
        logging:
            options:
                max-size: "1k"
                max-file: "1"
